[project]
name = "api-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lambert-19", email = "ndawseri@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "oracledb>=26.0.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.0",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
api-project = "api_project:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
