"""couverture des livres

Revision ID: 022aa2a0332d
Revises: c14cb6cea9ee
Create Date: 2026-10-02 11:47:01.143012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022aa2a0332d'
down_revision: Union[str, Sequence[str], None] = 'c14cb6cea9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couverture',
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.LargeBinary(), nullable=False),
    sa.Column('type_mime', sa.String(length=20), nullable=False),
    sa.Column('taille', sa.Integer(), nullable=False),
    sa.Column('date_maj', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['livre_id'], ['livre.id'], name=op.f('fk_couverture_livre_id_livre'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('livre_id', name=op.f('pk_couverture'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couverture')
    # ### end Alembic commands ###
