"""init

Revision ID: f44ce7845794
Revises: 
Create Date: 2026-10-01 14:25:36.591396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44ce7845794'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livre',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('auteur', sa.String(length=255), nullable=False),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('disponible', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_livre')),
    sa.UniqueConstraint('isbn', name=op.f('uq_livre_isbn'))
    )
    op.create_index(op.f('ix_livre_auteur'), 'livre', ['auteur'], unique=False)
    op.create_index(op.f('ix_livre_titre'), 'livre', ['titre'], unique=False)
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'membre', name='role', native_enum=False, create_constraint=False, length=10), server_default='membre', nullable=False),
    sa.Column('date_inscription', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'membre')", name=op.f('ck_utilisateur_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateur')),
    sa.UniqueConstraint('email', name=op.f('uq_utilisateur_email'))
    )
    op.create_table('emprunt',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('date_emprunt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_retour_prevue', sa.Date(), nullable=False),
    sa.Column('date_retour', sa.DateTime(), nullable=True),
    sa.CheckConstraint('date_retour IS NULL OR date_retour >= date_emprunt', name=op.f('ck_emprunt_dates_coherentes')),
    sa.ForeignKeyConstraint(['livre_id'], ['livre.id'], name=op.f('fk_emprunt_livre_id_livre')),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_emprunt_utilisateur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emprunt'))
    )
    op.create_index(op.f('ix_emprunt_livre_id'), 'emprunt', ['livre_id'], unique=False)
    op.create_index(op.f('ix_emprunt_utilisateur_id'), 'emprunt', ['utilisateur_id'], unique=False)
    op.create_index('uq_emprunt_livre_en_cours', 'emprunt', [sa.literal_column('CASE WHEN (date_retour IS NULL) THEN livre_id END')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_emprunt_livre_en_cours', table_name='emprunt')
    op.drop_index(op.f('ix_emprunt_utilisateur_id'), table_name='emprunt')
    op.drop_index(op.f('ix_emprunt_livre_id'), table_name='emprunt')
    op.drop_table('emprunt')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_livre_titre'), table_name='livre')
    op.drop_index(op.f('ix_livre_auteur'), table_name='livre')
    op.drop_table('livre')
    # ### end Alembic commands ###
