"""ajout genre livre

Revision ID: c14cb6cea9ee
Revises: f44ce7845794
Create Date: 2026-10-01 14:37:19.843636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14cb6cea9ee'
down_revision: Union[str, Sequence[str], None] = 'f44ce7845794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livre', sa.Column('genre', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_livre_genre'), 'livre', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livre_genre'), table_name='livre')
    op.drop_column('livre', 'genre')
    # ### end Alembic commands ###
